title: Another Security Blog
description: A place to show my mad skills.
show_pages: true
google_analytics:
theme: jekyll-theme-hacker
website: https://cybercasquatch.github.io
basewebsite: /blog
permalink: /:categories/:year/:month/:day/:title:output_ext
